--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4 (Debian 16.4-1.pgdg110+2)
-- Dumped by pg_dump version 16.4 (Debian 16.4-1.pgdg110+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cv_points; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cv_points (
    id bigint NOT NULL,
    dataset_id text NOT NULL,
    ts timestamp with time zone,
    lat double precision NOT NULL,
    lon double precision NOT NULL,
    geom public.geometry(Point,4326),
    road_segment_id text,
    road_dist_m double precision,
    road_conf double precision,
    attrs jsonb DEFAULT '{}'::jsonb,
    geom_m public.geometry(Point,26915)
);


ALTER TABLE public.cv_points OWNER TO postgres;

--
-- Name: cv_points_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.cv_points_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.cv_points_id_seq OWNER TO postgres;

--
-- Name: cv_points_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.cv_points_id_seq OWNED BY public.cv_points.id;


--
-- Name: cv_points_sample_medium; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cv_points_sample_medium (
    id bigint NOT NULL,
    dataset_id text,
    ts timestamp with time zone,
    lat double precision,
    lon double precision,
    geom public.geometry(Point,4326),
    road_segment_id text,
    attrs jsonb,
    road_dist_m double precision,
    road_conf double precision,
    geom_m public.geometry(Point,26915)
);


ALTER TABLE public.cv_points_sample_medium OWNER TO postgres;

--
-- Name: cv_hard_brake; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cv_hard_brake (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cv_point_id bigint NOT NULL,
    dataset_id text NOT NULL,
    ts timestamp with time zone,
    lat double precision NOT NULL,
    lon double precision NOT NULL,
    geom public.geometry(Point,4326),
    geom_m public.geometry(Point,26915),
    road_segment_id text,
    road_dist_m double precision,
    road_conf double precision,
    acc_x double precision,
    acc_y double precision,
    speed double precision,
    speed_limit double precision,
    speed_over_limit double precision,
    attrs jsonb DEFAULT '{}'::jsonb
);


ALTER TABLE public.cv_hard_brake OWNER TO postgres;

--
-- Name: datasets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.datasets (
    dataset_id text NOT NULL,
    session_id text NOT NULL,
    name text NOT NULL,
    entity_type text,
    status text DEFAULT 'ready'::text NOT NULL,
    mapping jsonb DEFAULT '{}'::jsonb,
    provenance jsonb DEFAULT '[]'::jsonb,
    stats jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.datasets OWNER TO postgres;

--
-- Name: events; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.events (
    id bigint NOT NULL,
    dataset_id text NOT NULL,
    session_id text NOT NULL,
    ts timestamp with time zone,
    lat double precision,
    lon double precision,
    geom public.geometry(Point,4326),
    geom_m public.geometry(Point,26915),
    road_segment_id text,
    road_dist_m double precision,
    road_conf double precision,
    props jsonb DEFAULT '{}'::jsonb NOT NULL
);


ALTER TABLE public.events OWNER TO postgres;

--
-- Name: events_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.events_id_seq OWNER TO postgres;

--
-- Name: events_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.events_id_seq OWNED BY public.events.id;


--
-- Name: roads; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roads (
    road_segment_id text NOT NULL,
    name text,
    geom public.geometry(MultiLineString,4326),
    attrs jsonb DEFAULT '{}'::jsonb,
    geom_m public.geometry(MultiLineString,26915)
);


ALTER TABLE public.roads OWNER TO postgres;

--
-- Name: cv_points id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_points ALTER COLUMN id SET DEFAULT nextval('public.cv_points_id_seq'::regclass);


--
-- Name: events id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events ALTER COLUMN id SET DEFAULT nextval('public.events_id_seq'::regclass);


--
-- Name: cv_points_sample_medium cv_points_sample_medium_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_points_sample_medium
    ADD CONSTRAINT cv_points_sample_medium_pkey PRIMARY KEY (id);


--
-- Name: datasets datasets_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.datasets
    ADD CONSTRAINT datasets_pkey PRIMARY KEY (dataset_id);


--
-- Name: events events_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);


--
-- Name: roads roads_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roads
    ADD CONSTRAINT roads_pkey PRIMARY KEY (road_segment_id);


--
-- Name: cv_points_new_join_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cv_points_new_join_idx ON public.cv_points USING btree (dataset_id, road_segment_id, ts);


--
-- Name: datasets_session_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX datasets_session_idx ON public.datasets USING btree (session_id);

--
-- Name: cv_hard_brake indexes; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cv_hard_brake_dataset_ts_idx ON public.cv_hard_brake USING btree (dataset_id, ts);
CREATE INDEX cv_hard_brake_road_idx ON public.cv_hard_brake USING btree (road_segment_id);
CREATE INDEX cv_hard_brake_geom_gist_idx ON public.cv_hard_brake USING gist (geom);
CREATE INDEX cv_hard_brake_geom_m_gist_idx ON public.cv_hard_brake USING gist (geom_m);


--
-- Name: events_dataset_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX events_dataset_idx ON public.events USING btree (dataset_id);


--
-- Name: events_geom_m_gist; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX events_geom_m_gist ON public.events USING gist (geom_m);


--
-- Name: events_join_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX events_join_idx ON public.events USING btree (dataset_id, road_segment_id, ts);


--
-- Name: events_road_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX events_road_idx ON public.events USING btree (dataset_id, road_segment_id);


--
-- Name: events_session_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX events_session_idx ON public.events USING btree (session_id);


--
-- Name: events_ts_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX events_ts_idx ON public.events USING btree (dataset_id, ts);


--
-- Name: idx_cv_new_dataset_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_cv_new_dataset_id ON public.cv_points USING btree (dataset_id);


--
-- Name: idx_cv_new_geom_gist; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_cv_new_geom_gist ON public.cv_points USING gist (geom);


--
-- Name: idx_cv_new_geom_m_gist; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_cv_new_geom_m_gist ON public.cv_points USING gist (geom_m);


--
-- Name: idx_cv_new_road_segment_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_cv_new_road_segment_id ON public.cv_points USING btree (road_segment_id);


--
-- Name: idx_cv_new_ts; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_cv_new_ts ON public.cv_points USING btree (ts);


--
-- Name: idx_cv_sample_medium_geom; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_cv_sample_medium_geom ON public.cv_points_sample_medium USING gist (geom);


--
-- Name: idx_roads_geom_gist; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_roads_geom_gist ON public.roads USING gist (geom);


--
-- Name: idx_roads_geom_m_gist; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_roads_geom_m_gist ON public.roads USING gist (geom_m);

--
-- Name: cv_road_agg; Type: TABLE; Schema: public; Owner: postgres
-- Purpose: Precomputed CV road aggregates (avg/min/max speed + date range)
--

CREATE TABLE public.cv_road_agg (
    dataset_id text NOT NULL,
    road_segment_id text NOT NULL,
    road_name text,
    avg_speed numeric,
    speed_limit_p50 numeric,
    speed_limit_p90 numeric,
    speed_limit_mode numeric,
    min_speed numeric,
    max_speed numeric,
    start_ts timestamp with time zone,
    end_ts timestamp with time zone,
    point_count integer,
    geom public.geometry(MultiLineString,4326),
    updated_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.cv_road_agg OWNER TO postgres;

--
-- Name: cv_road_agg_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cv_road_agg
    ADD CONSTRAINT cv_road_agg_pkey PRIMARY KEY (dataset_id, road_segment_id);

--
-- Name: idx_cv_road_agg_dataset_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_cv_road_agg_dataset_id ON public.cv_road_agg USING btree (dataset_id);

--
-- Name: idx_cv_road_agg_geom_gist; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_cv_road_agg_geom_gist ON public.cv_road_agg USING gist (geom);


--
-- PostgreSQL database dump complete
--
